test_task:
  container:
    image: elixir:1.10.3
    image: postgres:12.3
  install_hex_script:
     - mix local.hex --force
     - mix local.rebar --force
  mix_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script: mix deps.get
  compile_script: mix compile
  test_script: mix test
