test_task:
  container:
    image: elixir:1.10.3
  env:
     MIX_ENV: test

  install_hex_script:
     - mix local.hex --force
     - mix local.rebar --force

  mix_cache:
    folder: deps
    fingerprint_script: cat mix.lock
    populate_script: 
      - mix deps.get
      - mix compile

db_task:
  container:
     additional_containers:
       - name: postgres 
         image: postgres:12.3
         port: 5432
         env:
            POSTGRES_USER: xavvvier
            POSTGRES_DB: helix_test
            POSTGRES_PASSWORD:
  migrate_db_script:
     - mix ecto.create
     - mix ecto.migrate
     - mix run apps/builder/priv/repo/seeds.exs

  test_script: mix test
